steps:
  - name: 'node:18'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm install -g eas-cli
        npm install
        eas build --platform android --profile preview --non-interactive --no-wait
    env:
      - 'EXPO_TOKEN=${_EXPO_TOKEN}'
      - 'EAS_NO_VCS=1'
timeout: 600s